apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devops-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ujjalkumarsharma/devops-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://admin:password@mongo:27017
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
