pipeline {
  agent any

  environment {
    DOCKERHUB_CREDS = credentials('dockerhub-creds')
    DOCKERHUB_USER = "${DOCKERHUB_CREDS_USR}"
    DOCKERHUB_PASS = "${DOCKERHUB_CREDS_PSW}"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

   stage('Build Frontend Image') {
  steps {
    sh '''
      docker build -f docker/frontend.Dockerfile \
      -t $DOCKERHUB_USER/devops-frontend:latest $WORKSPACE
    '''
  }
}

stage('Build Backend Image') {
  steps {
    sh '''
      docker build -f docker/backend.Dockerfile \
      -t $DOCKERHUB_USER/devops-backend:latest $WORKSPACE
    '''
  }
}


    stage('Login to Docker Hub') {
      steps {
        sh '''
          echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
        '''
      }
    }

    stage('Push Images') {
      steps {
        sh '''
          docker push $DOCKERHUB_USER/devops-frontend:latest
          docker push $DOCKERHUB_USER/devops-backend:latest
        '''
      }
    }
  }

  post {
    success {
      echo 'CI pipeline completed successfully'
    }
    failure {
      echo 'CI pipeline failed'
    }
  }
}
